- name: Copying VMWare Tools source
  copy:
   src: VMwareTools-10.0.10-4301679.tar.gz
   dest: /tmp

- name: Configuring & Installing VMWare Tools
  command: '{{ item }} chdir=/tmp/ warn=no'
  with_items:
   - tar -zxvf VMwareTools-10.0.10-4301679.tar.gz
   - ./vmware-tools-distrib/vmware-install.pl --default
   - /usr/bin/vmware-config-tools.pl -default
   - /etc/vmware-tools/services.sh restart

- name: Cleaning up temporary directories
  command: '{{ item }} chdir=/tmp/ warn=no'
  with_items:
   - rm -rf vmware-tools-distrib/
   - rm -f VMwareTools-10.0.10-4301679.tar.gz