- name: Removing current Timezone
  file:
   path: /etc/localtime
   state: absent
   
- name: Setting up system Timezone to Kolkata
  file:
   src: /usr/share/zoneinfo/Asia/Kolkata
   dest: /etc/localtime
   state: link